apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-iykb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-iykb
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-iykb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-iykb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-iykb
    spec:
      containers:
      - image: quay.io/pkumari_org/e2e-demos-bvof-tenant/status-quarkus-io/statusquarkusio-iykb@sha256:3eddb10601b3057f7856202fe406c0d03c6ddd0f63a03f1a571dd0ebd1573e07
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
